image: maven:latest

stages:
  - build
  - test

variables:
  MAVEN_CLI_OPTS: "-B -ntp"

cache:
  key: maven
  paths:
    - .m2/repository

before_script:
  - echo "Using Java version:"
  - java -version
  - echo "Using Maven version:"
  - mvn -version

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean package
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 day

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    reports:
      junit: target/surefire-reports/*.xml
    expire_in: 1 day

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
  script:
    - echo "Preparing release..."
    - mvn $MAVEN_CLI_OPTS deploy # Modify if using GitLab Package Registry or Nexus
  release: # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'