image: maven:latest

stages:
  - build
  - test

variables:
  MAVEN_CLI_OPTS: "-B -ntp"

cache:
  key: maven
  paths:
    - .m2/repository

before_script:
  - echo "Using Java version:"
  - java -version
  - echo "Using Maven version:"
  - mvn -version

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean package
  artifacts:
    paths:
      - target/JavaLab1-app.jar
      - target/JavaLab1-data-generator.jar
      - target/JavaLab4-client.jar
      - target/JavaLab4-server.jar
    expire_in: 1 day

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    reports:
      junit: target/surefire-reports/*.xml
    expire_in: 1 day